version: "3"

services:
  nbxplorer:
    restart: always
    ports: 
      - 32838:32838
    build:
      context: .
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_NOAUTH: 1
      NBXPLORER_CHAINS: "btc,lbtc"
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
      NBXPLORER_BTCRPCUSER: liquid
      NBXPLORER_BTCRPCPASSWORD: liquid
      NBXPLORER_RMQHOST: rabbitmq
      NBXPLORER_RMQVIRTUAL: / 
      NBXPLORER_RMQUSER: guest
      NBXPLORER_RMQPASS: guest
      NBXPLORER_RMQTRANEX: NewTransaction
      NBXPLORER_RMQBLOCKEX: NewBlock
      NBXPLORER_LBTCRPCURL: http://elementsd-liquid:43783/
      NBXPLORER_LBTCNODEENDPOINT: elementsd-liquid:39389
    volumes:
      - "nbxplorer_datadir:/datadir"
      - "bitcoin_datadir:/root/.bitcoin"
      - "elementsd_liquid_datadir:/root/.elements"
    links:
      - bitcoind
      - rabbitmq

  bitcoind:
    restart: always
    container_name: btcpayserver_bitcoind
    image: btcpayserver/bitcoin:0.18.0-1
    environment:
      BITCOIN_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        rpcbind=0.0.0.0:43782
        port=39388
        whitelist=0.0.0.0/0
        rpcauth=liquid:c8bf1a8961d97f224cb21224aaa8235d$$402f4a8907683d057b8c58a42940b6e54d1638322a42986ae28ebb844e603ae6
    expose:
    - "43782"
    - "39388"
    ports:
      - "43782:43782"
      - "39388:39388"
    volumes:
    - "bitcoin_datadir:/data"

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15672:15672
      
  elementsd-liquid:
    restart: always
    container_name: btcpayserver_elementsd_liquid
    image: btcpayserver/elements:0.18.1.7
    environment:
      ELEMENTS_CHAIN: elementsregtest
      ELEMENTS_EXTRA_ARGS: |
        mainchainrpcport=43782
        mainchainrpchost=bitcoind
        mainchainrpcuser=liquid
        mainchainrpcpassword=liquid
        rpcport=19332
        rpcbind=0.0.0.0:19332
        rpcauth=liquid:c8bf1a8961d97f224cb21224aaa8235d$$402f4a8907683d057b8c58a42940b6e54d1638322a42986ae28ebb844e603ae6
        port=19444
        whitelist=0.0.0.0/0
        validatepegin=0
        initialfreecoins=210000000000000
        con_dyna_deploy_start=99999999999
    expose:
      - "19332"
      - "19444"
    ports:
      - "19332:19332"
      - "19444:19444"
    volumes:
      - "elementsd_liquid_datadir:/data"
    
volumes:
  nbxplorer_datadir: 
  bitcoin_datadir:
  elementsd_liquid_datadir: 
